config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#index"
  resources :menus

  namespace :api do
    namespace :menu do
      resources :positions, only: [:update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  acts_as_list
  validates :title, presence: true, length: { maximum: 50 }
  validates :price, presence: true, numericality: { only_integer: true }

  scope :sorted, -> { order(position: :asc) }
end

app/controllers/api/menu/positions_controller.rb
class Api::Menu::PositionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def update
    menu = Menu.find_by!(position: params[:from].to_i + 1)
    menu.update!(position: params[:to].to_i + 1) # SortableのnewInbexは0から始まるから
    head :ok
  end
end

app/controllers/api/menus_controller.rb
class Api::MenusController < ApplicationController
  skip_before_action :verify_authenticity_token

  def update
    menu = Menu.find_by!(position: params[:from].to_i + 1)
    menu.update!(position: params[:to].to_i + 1) # SortableのnewInbexは0から始まるから
    head :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[show edit update destroy]

  # GET /menus or /menus.json
  def index
    @menus = Menu.sorted
  end

  # GET /menus/1 or /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus or /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: "Menu was successfully created." }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1 or /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: "Menu was successfully updated." }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1 or /menus/1.json
  def destroy
    @menu.destroy!
    respond_to do |format|
      format.html { redirect_to menus_url, notice: "Menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:title, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv": "Content-Type" }/
    %title Demo
    %meta{ content: "width=device-width,initial-scale=1", name: "viewport" }/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"
  %body
    = yield

app/views/menus/_form.html.haml
= form_for menu do |f|
  - if menu.errors.any?
    #error-explanation
      %h2
        #{pluralize(menu.errors.count, "error")} prohibited this menu from being saved:
      %ul
        - menu.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :price
    = f.number_field :price
  .actions
    = f.submit "Save"

app/views/menus/edit.html.haml
%h1 Editing menu

= render "form", menu: @menu

= link_to "Show", @menu
\|
= link_to "Back", menus_path

app/views/menus/index.html.haml
= javascript_pack_tag "views/menus/index", "data-turbolinks-track": "reload"
%h1 Listing menus

%table
  %thead
    %tr
      %th
      %th Title
      %th Price
      %th
      %th
      %th

  %tbody#js-sortable-menus
    - @menus.each do |menu|
      %tr
        %td
          %i.handle
            .fa.fa-list-ul
        %td= menu.title
        %td= menu.price
        %td= link_to "Show", menu
        %td= link_to "Edit", edit_menu_path(menu)
        %td= link_to "Destroy", menu, method: :delete, data: { confirm: "Are you sure?" }

%br

= link_to "New Menu", new_menu_path

app/views/menus/new.html.haml
%h1 New menu

= render "form", menu: @menu

= link_to "Back", menus_path

app/views/menus/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @menu.title
%p
  %b Price:
  = @menu.price

= link_to "Edit", edit_menu_path(@menu)
\|
= link_to "Back", menus_path

app/views/static_pages/index.html.haml
%h1 Demo App
%p Hello World!

= link_to "Menu", menus_path